apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-app
  template:
    metadata:
      labels:
        app: shop-app
    spec:
      containers:
        - name: shop-app-api
          image: ethans333/shop-app_api:latest
          imagePullPolicy: Never
          env:
            - name: DATABASE_URL
              value: postgres://user:password@postgres:5432/shopdb
          ports:
            - containerPort: 8080
